2021-10-08 07:29:45.890224 (MainThread): Running with dbt=0.21.0
2021-10-08 07:29:48.344662 (MainThread): running dbt with arguments Namespace(record_timing_info=None, debug=False, log_format='default', write_json=True, use_colors=None, strict=False, warn_error=False, partial_parse=None, single_threaded=False, test_new_parser=False, use_experimental_parser=False, project_dir=None, profiles_dir='/Users/zoltancsonka/.dbt', profile='fission', target=None, vars='{}', log_cache_events=False, use_cache=True, fail_fast=False, threads=None, version_check=True, select=None, exclude=None, selector_name=None, state=None, defer=None, full_refresh=False, cls=<class 'dbt.task.run.RunTask'>, which='run', rpc_method='run')
2021-10-08 07:29:48.347320 (MainThread): Tracking: tracking
2021-10-08 07:29:48.347877 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097edc40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097edc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097dcb20>]}
2021-10-08 07:29:48.392953 (MainThread): Partial parsing not enabled
2021-10-08 07:29:48.467042 (MainThread): Parsing macros/catalog.sql
2021-10-08 07:29:48.469815 (MainThread): Parsing macros/adapters.sql
2021-10-08 07:29:48.512680 (MainThread): Parsing macros/materializations/merge.sql
2021-10-08 07:29:48.516741 (MainThread): Parsing macros/materializations/seed.sql
2021-10-08 07:29:48.521362 (MainThread): Parsing macros/materializations/view.sql
2021-10-08 07:29:48.522891 (MainThread): Parsing macros/materializations/table.sql
2021-10-08 07:29:48.526144 (MainThread): Parsing macros/materializations/incremental.sql
2021-10-08 07:29:48.535177 (MainThread): Parsing macros/core.sql
2021-10-08 07:29:48.538898 (MainThread): Parsing macros/materializations/test.sql
2021-10-08 07:29:48.546022 (MainThread): Parsing macros/materializations/helpers.sql
2021-10-08 07:29:48.556051 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-10-08 07:29:48.557791 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-10-08 07:29:48.575491 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-10-08 07:29:48.608357 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-10-08 07:29:48.631492 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-10-08 07:29:48.633346 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-10-08 07:29:48.644365 (MainThread): Parsing macros/materializations/incremental/on_schema_change.sql
2021-10-08 07:29:48.664151 (MainThread): Parsing macros/materializations/common/merge.sql
2021-10-08 07:29:48.678267 (MainThread): Parsing macros/materializations/table/table.sql
2021-10-08 07:29:48.686245 (MainThread): Parsing macros/materializations/view/view.sql
2021-10-08 07:29:48.693551 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-10-08 07:29:48.697422 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-10-08 07:29:48.698902 (MainThread): Parsing macros/etc/query.sql
2021-10-08 07:29:48.699865 (MainThread): Parsing macros/etc/is_incremental.sql
2021-10-08 07:29:48.701368 (MainThread): Parsing macros/etc/datetime.sql
2021-10-08 07:29:48.710644 (MainThread): Parsing macros/etc/where_subquery.sql
2021-10-08 07:29:48.712580 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-10-08 07:29:48.715124 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-10-08 07:29:48.716756 (MainThread): Parsing macros/adapters/common.sql
2021-10-08 07:29:48.772058 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-10-08 07:29:48.773789 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-10-08 07:29:48.774968 (MainThread): Parsing macros/schema_tests/unique.sql
2021-10-08 07:29:48.776285 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-10-08 07:29:48.977230 (MainThread): Acquiring new snowflake connection "model.sqlfluff.test".
2021-10-08 07:29:48.988464 (MainThread): Acquiring new snowflake connection "model.sqlfluff.dim_customer".
2021-10-08 07:29:49.068205 (MainThread): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3631912c-0341-4010-ae5d-a50d1da6522e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109ed26a0>]}
2021-10-08 07:29:49.074097 (MainThread): write_gpickle is deprecated and will be removed in 3.0.Use ``pickle.dump(G, path, protocol)``
2021-10-08 07:29:49.074567 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '3631912c-0341-4010-ae5d-a50d1da6522e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109ed26d0>]}
2021-10-08 07:29:49.074920 (MainThread): Found 2 models, 0 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-10-08 07:29:49.076347 (MainThread): 
2021-10-08 07:29:49.076790 (MainThread): Acquiring new snowflake connection "master".
2021-10-08 07:29:49.077777 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "list_DV_PROTOTYPE_DB".
2021-10-08 07:29:49.096074 (ThreadPoolExecutor-0_0): Using snowflake connection "list_DV_PROTOTYPE_DB".
2021-10-08 07:29:49.096348 (ThreadPoolExecutor-0_0): On list_DV_PROTOTYPE_DB: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "fission", "target_name": "dev", "connection_name": "list_DV_PROTOTYPE_DB"} */

    show terse schemas in database DV_PROTOTYPE_DB
    limit 10000
2021-10-08 07:29:49.096552 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2021-10-08 07:29:50.283006 (ThreadPoolExecutor-0_0): SQL status: SUCCESS 6 in 1.19 seconds
2021-10-08 07:29:50.285389 (ThreadPoolExecutor-0_0): On list_DV_PROTOTYPE_DB: Close
2021-10-08 07:29:50.606127 (ThreadPoolExecutor-1_0): Acquiring new snowflake connection "list_DV_PROTOTYPE_DB_DEMO".
2021-10-08 07:29:50.615552 (ThreadPoolExecutor-1_0): Using snowflake connection "list_DV_PROTOTYPE_DB_DEMO".
2021-10-08 07:29:50.615801 (ThreadPoolExecutor-1_0): On list_DV_PROTOTYPE_DB_DEMO: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "fission", "target_name": "dev", "connection_name": "list_DV_PROTOTYPE_DB_DEMO"} */

    show terse objects in DV_PROTOTYPE_DB.DEMO
2021-10-08 07:29:50.616012 (ThreadPoolExecutor-1_0): Opening a new connection, currently in state closed
2021-10-08 07:29:51.486608 (ThreadPoolExecutor-1_0): SQL status: SUCCESS 0 in 0.87 seconds
2021-10-08 07:29:51.488152 (ThreadPoolExecutor-1_0): On list_DV_PROTOTYPE_DB_DEMO: Close
2021-10-08 07:29:51.695531 (MainThread): 09:29:51 | Concurrency: 4 threads (target='dev')
2021-10-08 07:29:51.695924 (MainThread): 09:29:51 | 
2021-10-08 07:29:51.697520 (Thread-1): Began running node model.sqlfluff.dim_customer
2021-10-08 07:29:51.697941 (Thread-1): 09:29:51 | 1 of 2 START view model DEMO.dim_customer............................ [RUN]
2021-10-08 07:29:51.698197 (Thread-2): Began running node model.sqlfluff.test
2021-10-08 07:29:51.698647 (Thread-1): Acquiring new snowflake connection "model.sqlfluff.dim_customer".
2021-10-08 07:29:51.698989 (Thread-2): 09:29:51 | 2 of 2 START view model DEMO.test.................................... [RUN]
2021-10-08 07:29:51.699242 (Thread-1): Compiling model.sqlfluff.dim_customer
2021-10-08 07:29:51.699743 (Thread-2): Acquiring new snowflake connection "model.sqlfluff.test".
2021-10-08 07:29:51.701953 (Thread-1): Writing injected SQL for node "model.sqlfluff.dim_customer"
2021-10-08 07:29:51.702370 (Thread-2): Compiling model.sqlfluff.test
2021-10-08 07:29:51.704728 (Thread-2): Writing injected SQL for node "model.sqlfluff.test"
2021-10-08 07:29:51.705927 (Thread-1): finished collecting timing info
2021-10-08 07:29:51.706518 (Thread-2): finished collecting timing info
2021-10-08 07:29:51.761238 (Thread-1): Writing runtime SQL for node "model.sqlfluff.dim_customer"
2021-10-08 07:29:51.763726 (Thread-2): Writing runtime SQL for node "model.sqlfluff.test"
2021-10-08 07:29:51.765624 (Thread-2): Using snowflake connection "model.sqlfluff.test".
2021-10-08 07:29:51.766405 (Thread-1): Using snowflake connection "model.sqlfluff.dim_customer".
2021-10-08 07:29:51.766595 (Thread-2): On model.sqlfluff.test: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "fission", "target_name": "dev", "node_id": "model.sqlfluff.test"} */

  create or replace  view DV_PROTOTYPE_DB.DEMO.test  as (
    SELECT
    c AS bar,
    a + b AS foo
FROM my_table
  );
2021-10-08 07:29:51.766804 (Thread-1): On model.sqlfluff.dim_customer: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "fission", "target_name": "dev", "node_id": "model.sqlfluff.dim_customer"} */

  create or replace  view DV_PROTOTYPE_DB.DEMO.dim_customer  as (
    select
    customer.dim_customer_id,
    customer.customer_name,
    customer.is_active,
    customer.created_at
from customer
  );
2021-10-08 07:29:51.767012 (Thread-2): Opening a new connection, currently in state init
2021-10-08 07:29:51.767203 (Thread-1): Opening a new connection, currently in state closed
2021-10-08 07:29:52.605645 (Thread-1): Snowflake query id: 019f7741-3200-ec67-0000-26590223b5ee
2021-10-08 07:29:52.606015 (Thread-1): Snowflake error: 002003 (42S02): SQL compilation error:
Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.
2021-10-08 07:29:52.606406 (Thread-1): finished collecting timing info
2021-10-08 07:29:52.606773 (Thread-1): On model.sqlfluff.dim_customer: Close
2021-10-08 07:29:52.614881 (Thread-2): Snowflake query id: 019f7741-3200-ec62-0000-265902237d36
2021-10-08 07:29:52.615242 (Thread-2): Snowflake error: 002003 (42S02): SQL compilation error:
Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.
2021-10-08 07:29:52.615538 (Thread-2): finished collecting timing info
2021-10-08 07:29:52.615819 (Thread-2): On model.sqlfluff.test: Close
2021-10-08 07:29:52.791492 (Thread-1): Database Error in model dim_customer (models/dim_customer.sql)
  002003 (42S02): SQL compilation error:
  Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.
  compiled SQL at target/run/sqlfluff/models/dim_customer.sql
Traceback (most recent call last):
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 183, in exception_handler
    yield
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 721, in execute
    Error.errorhandler_wrapper(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/errors.py", line 258, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/errors.py", line 188, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): SQL compilation error:
Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 291, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 393, in run
    return self.execute(compiled_node, manifest)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/run.py", line 249, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 27, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 55, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 226, in execute
    return self.connections.execute(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 131, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 354, in add_query
    connection, cursor = super().add_query(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/Users/zoltancsonka/.pyenv/versions/3.9.1/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 200, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error in model dim_customer (models/dim_customer.sql)
  002003 (42S02): SQL compilation error:
  Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.
  compiled SQL at target/run/sqlfluff/models/dim_customer.sql
2021-10-08 07:29:52.799391 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '3631912c-0341-4010-ae5d-a50d1da6522e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109e5ddc0>]}
2021-10-08 07:29:52.799950 (Thread-1): 09:29:52 | 1 of 2 ERROR creating view model DEMO.dim_customer................... [ERROR in 1.10s]
2021-10-08 07:29:52.800257 (Thread-1): Finished running node model.sqlfluff.dim_customer
2021-10-08 07:29:52.810908 (Thread-2): Database Error in model test (models/test.sql)
  002003 (42S02): SQL compilation error:
  Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.
  compiled SQL at target/run/sqlfluff/models/test.sql
Traceback (most recent call last):
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 183, in exception_handler
    yield
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 721, in execute
    Error.errorhandler_wrapper(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/errors.py", line 258, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/errors.py", line 188, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): SQL compilation error:
Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 291, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 393, in run
    return self.execute(compiled_node, manifest)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/run.py", line 249, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 27, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 55, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 226, in execute
    return self.connections.execute(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 131, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 354, in add_query
    connection, cursor = super().add_query(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/Users/zoltancsonka/.pyenv/versions/3.9.1/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 200, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error in model test (models/test.sql)
  002003 (42S02): SQL compilation error:
  Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.
  compiled SQL at target/run/sqlfluff/models/test.sql
2021-10-08 07:29:52.811984 (Thread-2): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '3631912c-0341-4010-ae5d-a50d1da6522e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109e4a100>]}
2021-10-08 07:29:52.812470 (Thread-2): 09:29:52 | 2 of 2 ERROR creating view model DEMO.test........................... [ERROR in 1.11s]
2021-10-08 07:29:52.812734 (Thread-2): Finished running node model.sqlfluff.test
2021-10-08 07:29:52.814095 (MainThread): Acquiring new snowflake connection "master".
2021-10-08 07:29:52.814545 (MainThread): 09:29:52 | 
2021-10-08 07:29:52.814793 (MainThread): 09:29:52 | Finished running 2 view models in 3.74s.
2021-10-08 07:29:52.815029 (MainThread): Connection 'master' was properly closed.
2021-10-08 07:29:52.815317 (MainThread): Connection 'model.sqlfluff.dim_customer' was properly closed.
2021-10-08 07:29:52.815577 (MainThread): Connection 'model.sqlfluff.test' was properly closed.
2021-10-08 07:29:52.863053 (MainThread): 
2021-10-08 07:29:52.863404 (MainThread): Completed with 2 errors and 0 warnings:
2021-10-08 07:29:52.863695 (MainThread): 
2021-10-08 07:29:52.864005 (MainThread): Database Error in model dim_customer (models/dim_customer.sql)
2021-10-08 07:29:52.864272 (MainThread):   002003 (42S02): SQL compilation error:
2021-10-08 07:29:52.864524 (MainThread):   Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.
2021-10-08 07:29:52.864769 (MainThread):   compiled SQL at target/run/sqlfluff/models/dim_customer.sql
2021-10-08 07:29:52.865014 (MainThread): 
2021-10-08 07:29:52.865305 (MainThread): Database Error in model test (models/test.sql)
2021-10-08 07:29:52.865517 (MainThread):   002003 (42S02): SQL compilation error:
2021-10-08 07:29:52.865725 (MainThread):   Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.
2021-10-08 07:29:52.865941 (MainThread):   compiled SQL at target/run/sqlfluff/models/test.sql
2021-10-08 07:29:52.866159 (MainThread): 
Done. PASS=0 WARN=0 ERROR=2 SKIP=0 TOTAL=2
2021-10-08 07:29:52.866447 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109e8b610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109ec1490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109ed2520>]}
2021-10-08 07:29:52.866747 (MainThread): Flushing usage events
